site_name: Advanced Newsletter Management
site_description: 'A guide for the Advanced Newsletter Management extension.'
site_author: SYSTOPIA
repo_url: https://github.com/systopia/de.systopia.newsletter

theme:
  name: material

nav:
    - Home: index.md
    - Configuration: configuration.md
    - Usage: usage.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
